version: '3.4'
services:
  worker:
    build: .
    image: &img worker
    command: [celery, worker, --app=worker.app, -n worker@%h, --concurrency=1, --loglevel=INFO]
    environment: &env
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - beat
      - rabbitmq
    restart: 'no'
    volumes: 
      - ./app:/app

  beat:
    build: .
    image: *img
    command: [celery, beat, --app=worker.app, --loglevel=INFO]
    environment: *env
    depends_on: 
      - rabbitmq
    restart: 'no'
    volumes: 
      - ./app:/app

  rabbitmq:
    image: rabbitmq:3.7.8

